language: python
python:
  - "3.7"
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-tests
    packages:
    - gfortran
    - libblas-dev
    - liblapack-dev
    - libopenmpi-dev
    - openmpi-bin

install:
  - sudo apt-get update
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda config --add channels conda-forge
  - conda info -a
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION compilers mpi4py petsc4py numpy scipy matplotlib conda-build six numpydoc networkx pyparsing packaging snowballstemmer pandas openpyxl xlrd jinja2 git imagesize idna docutils chardet babel alabaster sphinx sphinxcontrib ipython cython swig make sphinxcontrib-bibtex pydoe2 jsonschema ruamel_yaml pyyaml mock pip nose networkx
  - conda activate test-environment
  - pip install simpy
  - sudo apt-get install gfortran
  - git clone https://github.com/OpenMDAO/pyoptsparse.git
  - cd pyoptsparse
  - python setup.py install
  - cd ..
  - git clone https://github.com/OpenMDAO/MBI.git
  - cd MBI
  - python setup.py build install
  - cd ..
  - git clone https://github.com/OpenMDAO/OpenMDAO.git;
  - cd OpenMDAO
  - pip install -e .
  - cd ..
  - pip install -e .

script:
  - cd test
  - pytest -vv --durations=0
