language: python

python:
  - "3.7"

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-tests
    packages:
    - gfortran
    - libblas-dev
    - liblapack-dev
    - libopenmpi-dev
    - openmpi-bin

before_install:
- wget "https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh" -O miniconda.sh
- bash miniconda.sh -b -p $HOME/miniconda
- source "$HOME/miniconda/etc/profile.d/conda.sh"
- export PATH=/home/travis/miniconda/bin:$PATH
- if  [ "$TRAVIS_REPO_SLUG" = "your-org/your_project" ] && [ "$TRAVIS_PULL_REQUEST" = "false" ]; then
    MASTER_BUILD=1;
  fi

install:
- conda config --set always_yes yes --set changeps1 no
- conda update -q conda
- conda config --add channels conda-forge
- conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION compilers mpi4py petsc4py numpy scipy matplotlib conda-build six numpydoc networkx pyparsing packaging snowballstemmer pandas openpyxl xlrd jinja2 git imagesize idna docutils chardet babel alabaster sphinx sphinxcontrib ipython cython swig make sphinxcontrib-bibtex pydoe2 jsonschema ruamel_yaml pyyaml
- conda activate test-environment
- conda install --yes python=$PY numpy scipy nose sphinx mock swig pip;
- pip install --upgrade pip
- sudo apt-get install gfortran
- pip install numpy==1.14.1
- pip install scipy==1.0.0
- pip install mpi4py
- pip install matplotlib
- pip install nose
- pip install networkx
- pip install testflo
- pip install pyyaml
- pip install coveralls
- pip install --user travis-sphinx;

# install pyoptsparse
- git clone https://github.com/OpenMDAO/pyoptsparse.git;
- cd pyoptsparse;
- python setup.py install;
- cd ..;

# install MBI
- git clone https://github.com/OpenMDAO/MBI.git;
- cd MBI;
- python setup.py build install;
- cd ..;

# install OpenMDAO in developer mode so we have access to its sphinx extensions
- git clone https://github.com/OpenMDAO/OpenMDAO.git;
- cd OpenMDAO;
- pip install -e .;
- cd ..;

- hash -r
- conda config --set always_yes yes --set changeps1 no
- conda update -q conda
- conda config --add channels conda-forge
# Useful for debugging any issues with conda
- conda info -a

- pip install simpy
- pip install -e .

script:
- cd test
- pytest -vv --durations=0 test/

after_success:
- if [ "$MASTER_BUILD" ] && [ "$UPLOAD_DOCS" ]; then
    travis-sphinx deploy;
  fi
- coveralls;
